package com.maogig.gigreader.core.common.io

import java.io.File
import java.io.FileOutputStream
import java.io.IOException
import java.io.OutputStream

/**
 * Owns the app-private directory holding imported documents (one canonical copy per document).
 *
 * Writes are crash-safe: content is streamed into a temp file inside [rootDir]/.incoming, synced to
 * disk, then atomically renamed to its final name. A crash mid-import leaves only a temp file, which
 * [cleanupIncoming] removes later; it can never leave a truncated file under a document's name.
 */
class DocumentFileStore(val rootDir: File) {
    private val incomingDir = File(rootDir, INCOMING_DIR)

    fun fileFor(relativePath: String): File {
        val file = File(rootDir, relativePath)
        // Defense in depth: stored paths are generated by us, but never let one escape the root.
        require(file.canonicalPath.startsWith(rootDir.canonicalPath + File.separator)) { "path escapes library root" }
        return file
    }

    fun newIncomingFile(): File {
        ensureDir(incomingDir)
        return File.createTempFile("import-", ".part", incomingDir)
    }

    /** Opens [file] for writing; [SyncingOutputStream.close] fsyncs before closing. */
    fun openForWrite(file: File): SyncingOutputStream = SyncingOutputStream(FileOutputStream(file))

    /**
     * Atomically moves a fully written [incoming] file to its final location for [documentId] and
     * returns the path to store in the database (relative to [rootDir]).
     */
    fun commit(incoming: File, documentId: String, extension: String = "pdf"): String {
        ensureDir(rootDir)
        val relative = "$documentId.$extension"
        val target = File(rootDir, relative)
        if (!incoming.renameTo(target)) {
            // renameTo can fail across mount points; both live in rootDir, so this means a real error.
            throw IOException("could not move imported file into the library")
        }
        return relative
    }

    fun delete(relativePath: String): Boolean = fileFor(relativePath).let { !it.exists() || it.delete() }

    /** Removes temp files left by interrupted imports that are older than [olderThanMillis]. */
    fun cleanupIncoming(nowMillis: Long, olderThanMillis: Long = 60 * 60 * 1000L): Int {
        val files = incomingDir.listFiles() ?: return 0
        return files.count { it.isFile && nowMillis - it.lastModified() > olderThanMillis && it.delete() }
    }

    /**
     * Deletes files in [rootDir] that no database row references (e.g. a crash between the rename in
     * [commit] and the database insert). [referenced] are relative paths of live documents. Only
     * files untouched for [olderThanMillis] are considered, so a document committed a moment ago
     * whose row is still being inserted is never at risk.
     */
    fun cleanupOrphans(referenced: Set<String>, nowMillis: Long, olderThanMillis: Long = 24 * 60 * 60 * 1000L): Int {
        val files = rootDir.listFiles() ?: return 0
        return files.count {
            it.isFile && it.name !in referenced && nowMillis - it.lastModified() > olderThanMillis && it.delete()
        }
    }

    fun usableSpace(): Long = (rootDir.takeIf { it.exists() } ?: rootDir.parentFile)?.usableSpace ?: 0L

    fun totalSize(): Long = rootDir.listFiles()?.filter { it.isFile }?.sumOf { it.length() } ?: 0L

    private fun ensureDir(dir: File) {
        if (!dir.isDirectory && !dir.mkdirs() && !dir.isDirectory) throw IOException("cannot create $dir")
    }

    companion object {
        const val INCOMING_DIR = ".incoming"
    }
}

/** Output stream that flushes and fsyncs the file descriptor on close, so a commit is durable. */
class SyncingOutputStream(private val out: FileOutputStream) : OutputStream() {
    override fun write(b: Int) = out.write(b)
    override fun write(b: ByteArray, off: Int, len: Int) = out.write(b, off, len)
    override fun flush() = out.flush()
    override fun close() {
        out.use {
            it.flush()
            it.fd.sync()
        }
    }
}
